name 'yum_package_hack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures yum_package_hack'
long_description 'Installs/Configures yum_package_hack'
version '0.1.0'
